openapi: 3.1.0
info:
  title: Brands API
  description: API endpoints for brand profile management
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

tags:
  - name: brands
    description: Brand profile operations

paths:
  /brands:
    get:
      summary: List brands
      description: Retrieve a paginated list of brands
      operationId: listBrands
      tags:
        - brands
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandListResponse'
    post:
      summary: Create brand
      description: Create a new brand profile
      operationId: createBrand
      tags:
        - brands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandCreate'
      responses:
        '201':
          description: Brand created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandResponse'

  /brands/{brand_id}:
    get:
      summary: Get brand
      description: Retrieve a specific brand by ID
      operationId: getBrand
      tags:
        - brands
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandResponse'
    put:
      summary: Update brand
      description: Update an existing brand profile
      operationId: updateBrand
      tags:
        - brands
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandUpdate'
      responses:
        '200':
          description: Brand updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandResponse'
    delete:
      summary: Delete brand
      description: Soft delete a brand (if not referenced by audit items)
      operationId: deleteBrand
      tags:
        - brands
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Brand deleted successfully
        '409':
          description: Brand is referenced by audit items and cannot be deleted

components:
  schemas:
    BrandCreate:
      type: object
      required:
        - name
        - registration_country
        - company_size
        - target_markets
      properties:
        name:
          type: string
          maxLength: 255
        registration_country:
          type: string
          description: ISO country code
        company_size:
          type: string
          enum: [Micro, SME, Large]
        target_markets:
          type: array
          items:
            type: string
          description: Array of ISO country codes

    BrandUpdate:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        registration_country:
          type: string
        company_size:
          type: string
          enum: [Micro, SME, Large]
        target_markets:
          type: array
          items:
            type: string

    BrandResponse:
      type: object
      required:
        - id
        - name
        - registration_country
        - company_size
        - target_markets
        - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        registration_country:
          type: string
        company_size:
          type: string
          enum: [Micro, SME, Large]
        target_markets:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          nullable: true

    BrandListResponse:
      type: object
      required:
        - items
        - total
        - limit
        - offset
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/BrandResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

