openapi: 3.1.0
info:
  title: Sustainability Criteria API
  description: API endpoints for sustainability criteria management
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

tags:
  - name: criteria
    description: Sustainability criteria operations

paths:
  /criteria:
    get:
      summary: List criteria
      operationId: listCriteria
      tags: [criteria]
      parameters:
        - name: domain
          in: query
          schema:
            type: string
            enum: [Social, Environmental, Governance]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriterionListResponse'
    post:
      summary: Create criterion
      operationId: createCriterion
      tags: [criteria]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriterionCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriterionResponse'

  /criteria/{criterion_id}:
    get:
      summary: Get criterion
      operationId: getCriterion
      tags: [criteria]
      parameters:
        - name: criterion_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriterionResponse'

components:
  schemas:
    CriterionCreate:
      type: object
      required:
        - code
        - name
        - description
        - domain
      properties:
        code:
          type: string
          description: Unique code (e.g., ENV-001)
        name:
          type: string
        description:
          type: string
        domain:
          type: string
          enum: [Social, Environmental, Governance]

    CriterionResponse:
      type: object
      required:
        - id
        - code
        - name
        - description
        - domain
        - created_at
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        description:
          type: string
        domain:
          type: string
          enum: [Social, Environmental, Governance]
        created_at:
          type: string
          format: date-time

    CriterionListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CriterionResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

